version: "3.9"

services:
  dashboard:
    build: dashboard
    ports:
      - 80:3000
    volumes:
      - ./youtube:/youtube

  api:
    build: api
    ports:
      - 5000:5000
    links:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - ./redis-data:/data
